name: Excercise1
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Run eslint
        run: npm run lint
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Run test
        run: npm test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy project
        run: |
             npm run build
             echo "${{ github.actor }}"