name: PR Checks
on:
  pull_request:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Get codes
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint
      - name: Run test
        run: npm test
      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@main
